### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by miljan-aleksic** [tlindig/position-calculator#6]
Hi Tobias, thank you very much for this plugin, it is very useful.

Did you considered dropping jQuery dependency? Nowdays being jQuery unnecessary in most of projects, it seems a good idea to keep the main plugin dependency free while still providing a jQuery Plugin Wrapper (or not). Anyway, that would be my feature request ;)

Thanks again!

**Comment by tlindig** [comment]
Yes, I totally agree with you.

Few weeks ago I start working on, but could not continue because of lack of time. 

So I will prioritize it higher and hope can be ship some results soon.

**Comment by miljan-aleksic** [comment]
I ended up using Teddler, so no rush on my part, but having a simple script doing one thing well, is always welcome. Keep it up and thanks :)
