### ISSUE TITLE
Uncaught TypeError: $.PositionCalculator is not a constructor

### ISSUE THREAD

**Issue by jeevasusej** [tlindig/position-calculator#7]
Uncaught TypeError: $.PositionCalculator is not a constructor

I am getting the above error. Please tell me how to solve.

Demo itself not working. Please check

http://jsbin.com/sifec/1/edit?html,css,js,output

**Comment by tlindig** [comment]
oh, seams that that is the problem: 
http://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github

so replace in the script-tag "raw.githubusercontent.com" with "rawgit.com" and it will work again.

**Comment by tlindig** [comment]
I replaced the link in the readme.
